export const initialData = {
  rows: [
    {
      id: 1,
      tier: "S",
      items: [],
      itemsContainerColor: "#1A1A1A",
      tierColor: "rgb(255, 127, 127)",
    },
    {
      id: 2,
      tier: "A",
      items: [],
      itemsContainerColor: "#1A1A1A",
      tierColor: "rgb(255, 191, 127)",
    },
    {
      id: 3,
      tier: "B",
      items: [],
      itemsContainerColor: "#1A1A1A",
      tierColor: "rgb(255, 223, 127)",
    },
    {
      id: 4,
      tier: "C",
      items: [],
      itemsContainerColor: "#1A1A1A",
      tierColor: "#FFFF7F",
    },
    {
      id: 5,
      tier: "D",
      items: [],
      itemsContainerColor: "#1A1A1A",
      tierColor: "rgb(191, 255, 127)",
    },
  ],
  items: [
    { id: 1, value: "Item" },
    { id: 2, value: "Item" },
    { id: 3, value: "Item" },
    { id: 4, value: "Item" },
    { id: 5, value: "Item" },
    { id: 6, value: "Item" },
    { id: 7, value: "Item" },
    { id: 8, value: "Item" },
    { id: 9, value: "Item" },
    { id: 10, value: "Item" },
  ],
};
